# /.github/workflows/daily.yml
# based on https://github.com/carbonphyber/watch-pge-electrical-outages/blob/main/.github/workflows/daily.yml
on:
  schedule:
    - cron:  '*/10 * * * *' # Every 10 minutes
name: Pull Data and Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Log Python location
      run: which python
    - name: Scrape
      run: |
        curl -o data/sce-electrical-outages-raw.json --no-progress-meter "https://prodms.dms.sce.com/outage/v1/power/outage?_=$(date +%s)"
    - name: Pretty Print the JSON
      run: |
        cat data/sce-electrical-outages-raw.json | python -m json.tool > data/sce-electrical-outages.json
    - name: Commit new data
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data/
        if [[ -n "$(git status -s -- data/)" ]]; then
          TIMESTAMP_NOW=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
          git commit -m "data scraped at $TIMESTAMP_NOW"
          git push
        fi
